AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Money Club Lamda protobuf.
Resources:
  LambdaSpringFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lamda.handler
      Runtime: nodejs8.10
      FunctionName: nodejs-express-protobuf-sample
      CodeUri: s3://spring-boot-amit1/0a2f970bc9f75f633b46baf872343a47
      MemorySize: 1024
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
Outputs:
  LambdaSpringBootApi:
    Description: URL for application
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/getcolor
    Export:
      Name: LambdaExpressProtobuffNodeApp
